packages:
    - packages/*
    - docs
    - registry-template

catalog:
    "@sveltejs/kit": ^2.42.0
    "@sveltejs/vite-plugin-svelte": ^6.2.1
    svelte: ^5.43.4
    svelte-check: ^4.3.3
    typescript: ^5.9.3
    vite: ^7.2.2
